language: node_js
node_js:
- stable
script:
- npm test
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: XsNLvlhSSsZqgRiBFjRNPryJNFWvonpftutrqIg0vQzlbHutAl91ULZJlQs55LT5wcCw0pZ9B/6xF3VDbKLaDHK5V3f3WWRwSFUA/VocZSOT2nNFrhEbEWHORIj++o7nIvWDksFPDYKNL6tx3GaV2xgFigIw2Qfovsa4QiCFQzca2FmVrT9m2G877bNLFLHmCfa2z4RHyA+CLwgUpUGYQ6pWPR4E3XbXckSfx8H77qurnfBdCzylpjIi3/S0ILAzBDAmLM7pPbHq2Uqt5y3SCjiDtsc82nLsl9N24vakaNwsVdzZOt9X9Up8a8gWxCQYEAct0gH/rtxDwuZWs1ACdcBRbFpC6d/kYGj9rIxA6pzP7de8Jt31kA85RULWN1aT7avn85J+vyg3t3vzmIEyye2kWMnP/Q0QPG5dmZN6qah2eP9WS1jCve6G3lVgpCxLn52XLpOHEFAJIbtfvfH5kqeHdoOkbT5I745+uSuo5p3xLaOUcavDldHBvrubROVaXPbJJswlp73rTkzfg1cPMg1GIaTB5OLyqbRkKG6bark5ptx+em2KgbVJiEn0CNQZcsb35P7VM3cG4G1vO/fiPU1uKPUtSOxTOBrv3tpdPLTmCsNlebXFuq0Cy2rjnsueAzOkZ7Kg5F1EX/SA+NNlWXKBMnA9vgy9gZtdd4EvbWw=
  on:
    branch: develop
after_success:
- npm run coverage
